### ISSUE TITLE
Can't access the GUI

### ISSUE THREAD

**Issue by nobbylark** [alturismo/xteve#5]
Hi

I've just set this up in docker for Synology. Configuration as follows:

![firefox_bhAJnliQ5G](https://user-images.githubusercontent.com/80721162/134905752-6e36d758-c1ff-4198-8b2d-9c07f36d8479.png)
![firefox_NYe83AT4PD](https://user-images.githubusercontent.com/80721162/134905769-62137bda-d25b-49bf-a94c-3e688b4f47b2.png)
![firefox_SPTRrqXRyW](https://user-images.githubusercontent.com/80721162/134905776-8bdcbb1c-7446-4cad-aca1-4b506bfcd9d1.png)

Error i get when i try to access the GUI:

![firefox_3MaTUqRKYx](https://user-images.githubusercontent.com/80721162/134905912-b1ddb9e9-4ae3-4e5c-b687-be1304f7c16c.png)

Added the log if that is of any use:

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/Jason/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/Jason/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">

date | stream | content
-- | -- | --
27/09/2021 12:15 | stdout | crond[8]:  line /config/cronjob.sh
27/09/2021 12:15 | stdout | crond[8]: file root:
27/09/2021 12:15 | stdout | crond[8]: wakeup dt=60
27/09/2021 12:14 | stdout | crond[8]:  line /config/cronjob.sh
27/09/2021 12:14 | stdout | crond[8]: file root:
27/09/2021 12:14 | stdout | crond[8]: wakeup dt=60
27/09/2021 12:13 | stdout | crond[8]:  line /config/cronjob.sh
27/09/2021 12:13 | stdout | crond[8]: file root:
27/09/2021 12:13 | stdout | crond[8]: wakeup dt=60
27/09/2021 12:12 | stdout | crond[8]:  line /config/cronjob.sh
27/09/2021 12:12 | stdout | crond[8]: file root:
27/09/2021 12:12 | stdout | crond[8]: wakeup dt=60
27/09/2021 12:11 | stdout | crond[8]:  line /config/cronjob.sh
27/09/2021 12:11 | stdout | crond[8]: file root:
27/09/2021 12:11 | stdout | crond[8]: wakeup dt=60
27/09/2021 12:10 | stdout | crond[8]:  line /config/cronjob.sh
27/09/2021 12:10 | stdout | crond[8]: file root:
27/09/2021 12:10 | stdout | crond[8]: wakeup dt=60
27/09/2021 12:09 | stdout | crond[8]:  line /config/cronjob.sh
27/09/2021 12:09 | stdout | crond[8]: file root:
27/09/2021 12:09 | stdout | crond[8]: wakeup dt=60
27/09/2021 12:08 | stdout | crond[8]:  line /config/cronjob.sh
27/09/2021 12:08 | stdout | crond[8]: file root:
27/09/2021 12:08 | stdout | crond[8]: wakeup dt=60
27/09/2021 12:08 | stdout | [0mcrond[8]: user:root entry:0    0  *  *    *  /config/cronjob.sh
27/09/2021 12:07 | stdout | [0m[32m2021/09/27 14:07:00 [xTeVe] Web Interface:          http://172.17.0.1:34400/web/ \|   xTeVe is also available via the other 7 IP's.
27/09/2021 12:07 | stdout | [0m[0m2021/09/27 14:07:00 [xTeVe] DVR IP:                 172.17.0.1:34400
27/09/2021 12:07 | stdout | [0m[0m2021/09/27 14:07:00 [xTeVe] Filter:                 0
27/09/2021 12:07 | stdout | [0m[0m2021/09/27 14:07:00 [xTeVe] Active streams:         0
27/09/2021 12:07 | stdout | [0m[0m2021/09/27 14:07:00 [xTeVe] All streams:            0
27/09/2021 12:07 | stdout | [0m[0m2021/09/27 14:07:00 [xTeVe] Unfiltered Chan. Limit: 480
27/09/2021 12:07 | stdout | [0m[0m2021/09/27 14:07:00 [xTeVe] Plex Channel Limit:     480
27/09/2021 12:07 | stdout | [0m[0m2021/09/27 14:07:00 [xTeVe] EPG Source:             PMS
27/09/2021 12:07 | stdout | [0m[0m2021/09/27 14:07:00 [xTeVe] Tuner (Plex / Emby):    1
27/09/2021 12:07 | stdout | [0m[0m2021/09/27 14:07:00 [xTeVe] UUID:                   2021-09-0KSG-6FK5U6
27/09/2021 12:07 | stdout | [0m[0m2021/09/27 14:07:00 [xTeVe] SSDP / DLNA:            true
27/09/2021 12:07 | stdout | [0m[0m2021/09/27 14:07:00 [xTeVe] Git Branch:             master [xteve-project]
27/09/2021 12:07 | stdout | [0m[0m2021/09/27 14:07:00 [xTeVe] GitHub:                   https://github.com/xteve-project
27/09/2021 12:07 | stdout | [0m[0m2021/09/27 14:07:00 [xTeVe] Temporary Folder:       /tmp/xteve/2021-09-0KSG-6FK5U6/
27/09/2021 12:07 | stdout | [0m[0m2021/09/27 14:07:00 [xTeVe] Load Settings:          /root/.xteve/settings.json
27/09/2021 12:07 | stdout | [0m[0m2021/09/27 14:07:00 [xTeVe] System Folder:          /root/.xteve/
27/09/2021 12:07 | stdout | [0m[0m2021/09/27 14:07:00 [xTeVe] Hostname:               xteve
27/09/2021 12:07 | stdout | [0m[0m2021/09/27 14:07:00 [xTeVe] System IP Addresses:    IPv4: 3 \| IPv6: 5
27/09/2021 12:07 | stdout | [0m[0m2021/09/27 14:07:00 [xTeVe] Database Version:       2.1.0
27/09/2021 12:07 | stdout | [0m[0m2021/09/27 14:07:00 [xTeVe] Version:                2.2.0 Build: 0200
27/09/2021 12:07 | stdout | [33m2021/09/27 14:07:00 [xTeVe] [WARNING] Don't run this as Root!
27/09/2021 12:07 | stdout |  
27/09/2021 12:07 | stdout | For help run: ./xteve -h
27/09/2021 12:07 | stdout | /config/cronjob.sh exist
27/09/2021 12:07 | stdout | crond[8]: user:root entry:0  0  *    *  *  /config/cronjob.sh
27/09/2021 12:07 | stdout | crond[8]: crond (busybox 1.33.1)   started, log level 2

</body>

</html>

**Comment by MaDTaZ** [comment]
you need to add /web to the end like this http://192.168.1.70:34400/web/.  You will to adjust the ip to what you have of course.

**Comment by nobbylark** [comment]
Yeah, I realised not long after raising this query. Sorry for not updating ! I'll close it.
